<?xml version="1.0"?>
<package format="3">
  <name>reactive_autonomy</name>
  <version>0.0.1</version>
  <description>Reactive LiDAR autonomy for F1TENTH (Follow-the-Gap + TTC + adaptive speed)</description>

  <maintainer email="you@todo.todo">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>ackermann_msgs</depend>

  <test_depend>ament_pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
