pure_pursuit:
  ros__parameters:
    #need rrt planner for /planned path
    amcl_topic: /amcl_pose
    drive_topic: /drive

    base_lookahead: 2.0 #1.1
    lookahead_speed_gain: 0.5 #0.4

    min_speed: 1.0 #1.0
    max_speed: 3.0 #1.5
    curvature_speed_gain: 4.0 #1.4

    wheelbase: 0.25
    max_steering_angle: 0.4189
    goal_tolerance: 0.30 #0.40

    control_rate_hz: 20.0
    loop_path: false

    steering_smoothing_alpha: 0.80

    path_timeout_sec: 1.0

    debug: true
    log_pose_every_n: 20
    log_control_every_n: 10