<?xml version="1.0"?>
<package format="3">
  <name>ttc_brake_manager</name>
  <version>0.0.1</version>
  <description>TTC-based brake manager with PS5 deadman (L1) and soft brake (L2) for F1TENTH.</description>

  <maintainer email="you@todo.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>ackermann_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
