wall_following:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/ackermann_cmd"

    target_distance: 0.55
    look_ahead: 0.9
    beam_a_id: 340.0
    beam_b_id: 300.0

    K_p: 0.9
    K_i: 0.0
    K_d: 0.25

    steer_limit_rad: 0.40
    i_limit: 1.0

    speed_straight: 2.0
    speed_medium: 1.5
    speed_turn: 1.0
    speed_hard_turn: 0.6

    th_straight: 0.10
    th_medium: 0.20
    th_turn: 0.30

    front_beam_id: 248.0
    front_clearance_m: 5.0