simple_driver:
  ros__parameters:
    scan_topic: /scan
    drive_topic: /drive #/ackermann_cmd 

    # Start slow. Tune upward only after it behaves safely.
    base_speed: 2.0
    turn_speed: 0.45
    stop_speed: 0.0

    # Steering tuning
    kp_centering: 0.25 #0.8
    kp_front_avoid: 0.25 #0.6
    max_steering_angle: 0.22 #0.34

    # Left wall sector
    left_min_angle_deg: 60.0
    left_max_angle_deg: 100.0

    # Right wall sector
    right_min_angle_deg: -100.0
    right_max_angle_deg: -60.0

    # Front obstacle sector
    front_min_angle_deg: -15.0
    front_max_angle_deg: 15.0

    # Safety thresholds
    front_slow_distance: 1.2
    front_stop_distance: 0.45

    # LiDAR filtering
    min_valid_range: 0.05
    max_valid_range: 10.0